### ISSUE TITLE
Need new Reddit icon in footer

### ISSUE THREAD

**Issue by lorezyra** [lorezyra/website#2]
Also, I've added Reddit for a forum. (Thinking to move away from FaceBook.)
Need to add the Reddit icon at the bottom next to the other social media icons.

![image](https://user-images.githubusercontent.com/1673222/114641739-a0a16700-9d0d-11eb-8dd1-39568d00808e.png)

**Comment by lorezyra** [comment]
Link for reddit is http://reddit.technocracy.works/

**Comment by bineshab** [comment]
Fixed Issue #2 - Added new Reddit icon in footer
