### ISSUE TITLE
donate button in smartphone view only

### ISSUE THREAD

**Issue by lorezyra** [lorezyra/website#4]
Add donate button in smartphone view only on index page. Donate button should link to donate page. In PC view, the donate button below share with friends should be invisible.

![image](https://user-images.githubusercontent.com/1673222/114735959-a2584280-9d80-11eb-960b-6b08c0970330.png)

![image](https://user-images.githubusercontent.com/1673222/114735918-9a989e00-9d80-11eb-966b-7c05c3707ecb.png)

**Comment by bineshab** [comment]
Fixed Issue #4 - Added donate button in smartphone view

![image](https://user-images.githubusercontent.com/82520967/114745852-b85c0800-9d6c-11eb-9391-01e709b5c9b7.png)
